import React, { useState } from 'react';
import { Image, Video, Mic, ShieldCheck, LogOut, User, Info, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import DetectionCard from './DetectionCard';

const Dashboard = () => {
    const navigate = useNavigate();
    const [showAbout, setShowAbout] = useState(false);
    const user = JSON.parse(localStorage.getItem('user') || 'null');

    const handleLogout = () => {
        localStorage.removeItem('user');
        navigate('/login');
    };

    return (
        <div className="min-h-screen bg-[#F5F5F7] text-[#1d1d1f]">
            {/* Navigation */}
            <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur-lg border-b border-gray-200/50">
                <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        <div className="bg-black text-white p-1.5 rounded-lg">
                            <ShieldCheck size={18} />
                        </div>
                        <span className="font-semibold text-lg tracking-tight">AI Content Detector</span>
                    </div>

                    <div className="flex items-center gap-6">
                        <div className="flex items-center gap-3">
                            <button
                                onClick={() => setShowAbout(true)}
                                className="text-sm font-medium text-gray-600 hover:text-black transition-colors flex items-center gap-1.5 mr-2"
                            >
                                <Info size={16} />
                                <span>About</span>
                            </button>
                            <div className="w-8 h-8 bg-gray-200 rounded-full flex items-center justify-center">
                                <User size={16} className="text-gray-500" />
                            </div>
                            {user && <span className="text-sm font-medium text-gray-700">{user}</span>}
                            <button
                                onClick={handleLogout}
                                className="text-sm font-medium text-gray-600 hover:text-red-500 transition-colors flex items-center gap-1.5 ml-4"
                            >
                                <LogOut size={16} />
                                <span>Logout</span>
                            </button>
                        </div>
                    </div>
                </div>
            </nav>

            {/* Header Section */}
            <header className="pt-24 pb-16 text-center max-w-2xl mx-auto px-6">
                <h1 className="text-4xl md:text-5xl font-bold mb-6 tracking-tight text-gray-900 leading-tight">
                    AI Manipulation <br />
                    <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">Detection Dashboard</span>
                </h1>
                <p className="text-lg text-gray-500 leading-relaxed">
                    Analyze images, videos, and audio files to instantly determine if they were created or altered using artificial intelligence models.
                </p>
            </header>

            {/* Main Content */}
            <main className="max-w-7xl mx-auto px-6 pb-24">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                    <DetectionCard
                        title="Image Analysis"
                        description="Upload JPG, PNG, or WEBP images to detect deepfake generation patterns and artifacts."
                        icon={Image}
                        type="image"
                        formats="JPG · PNG · WEBP"
                    />
                    <DetectionCard
                        title="Video Analysis"
                        description="Scan video files for AI-driven face swaps, lip-sync manipulation, and synthetic generation."
                        icon={Video}
                        type="video"
                        formats="MP4 · MOV · WEBM"
                    />
                    <DetectionCard
                        title="Audio Analysis"
                        description="Identify cloned voices and synthetic speech generated by TTS (Text-to-Speech) models."
                        icon={Mic}
                        type="audio"
                        formats="MP3 · WAV · M4A"
                    />
                </div>
            </main>

            <footer className="text-center py-8 text-gray-400 text-sm border-t border-gray-200">
                <p>© 2026 AI Content Guard. All rights reserved.</p>
            </footer>

            {/* About Modal */}
            {showAbout && (
                <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/30 backdrop-blur-sm transition-all">
                    <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full p-8 relative animate-in fade-in zoom-in duration-200">
                        <button
                            onClick={() => setShowAbout(false)}
                            className="absolute top-4 right-4 p-2 hover:bg-gray-100 rounded-full transition-colors text-gray-500 hover:text-gray-900"
                        >
                            <X size={20} />
                        </button>

                        <div className="flex items-center gap-3 mb-6">
                            <div className="p-2.5 bg-blue-50 text-blue-600 rounded-xl">
                                <Info size={24} />
                            </div>
                            <h2 className="text-2xl font-bold text-gray-900">About This Project</h2>
                        </div>

                        <div className="prose prose-gray max-w-none text-gray-600 leading-relaxed space-y-4">
                            <p>
                                I am building a student-level web application that focuses on detecting AI-generated and manipulated audio content using machine learning–based detection APIs.
                            </p>
                            <p>
                                The goal of this project is to understand how modern AI systems can identify synthetic or deepfake audio and to demonstrate these capabilities in an educational setting.
                            </p>
                            <p className="font-medium text-gray-800 bg-gray-50 p-4 rounded-lg border border-gray-100">
                                The API will be used strictly for academic learning, project demonstrations, and experimentation, not for commercial deployment or misuse.
                            </p>
                        </div>

                        <div className="mt-8 flex justify-end">
                            <button
                                onClick={() => setShowAbout(false)}
                                className="bg-black text-white px-6 py-2.5 rounded-xl font-medium hover:bg-gray-800 transition-colors"
                            >
                                Close
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Dashboard;
